id: envio_auditoria
namespace: company.team

triggers:
  - id: agendamento_horario
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "30 7-17 * * 1-6"
    timezone: "America/Sao_Paulo"

  - id: trigger_webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: H8FGQq2q

tasks:
  - id: wdir
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: sync_github
        type: io.kestra.plugin.git.SyncNamespaceFiles
        username: "{{ kv('GITHUB_USER') }}"
        password: "{{ kv('GITHUB_PASS') }}"
        url: https://github.com/raffaelhfarias/auto_kestra
        branch: main
        namespace: company.team
        gitDirectory: .
        dryRun: false

      - id: processar_auditoria
        type: io.kestra.plugin.scripts.python.Commands
        containerImage: mcr.microsoft.com/playwright/python:v1.57.0-noble
        env:
          VIDIBR_USER: "{{ kv('VIDIBR_USER') }}"
          VIDIBR_PASS: "{{ kv('VIDIBR_PASS') }}"
          ESTADO_ANTERIOR: "{{ kv('ULTIMO_VIDIBR_FORM') | default('') }}"
        beforeCommands:
          - |
            # Recupera o estado do KV Store do Kestra
            echo "$ESTADO_ANTERIOR" > ultimo_formulario.txt
            if [ -n "$ESTADO_ANTERIOR" ]; then
              echo "✓ Estado KV recuperado: $ESTADO_ANTERIOR"
            else
              echo "✓ Primeira execução detectada (KV vazio)."
            fi
          - pip install -r flow_envio_auditoria/requirements.txt
        commands:
          - export PYTHONPATH=flow_envio_auditoria && python flow_envio_auditoria/workflow/scripts/vidibr/processar_auditoria.py
        outputFiles:
          - "novo_formulario.json"
          - "ultimo_formulario.txt"

      - id: salvar_estado_kv
        type: io.kestra.plugin.core.kv.Set
        key: ULTIMO_VIDIBR_FORM
        value: "{{ read(outputs.processar_auditoria.outputFiles['ultimo_formulario.txt']) }}"

      - id: enviar_whatsapp
        type: io.kestra.plugin.scripts.python.Commands
        containerImage: python:3.11-slim
        inputFiles:
          novo_formulario.json: "{{ outputs.processar_auditoria.outputFiles['novo_formulario.json'] }}"
        env:
          EVOLUTION_API_URL: "{{ kv('EVOLUTION_API_URL') }}"
          EVOLUTION_API_KEY: "{{ kv('EVOLUTION_API_KEY') }}"
          EVOLUTION_INSTANCE: "{{ kv('EVOLUTION_INSTANCE') }}"
          WHATSAPP_GROUP_ID: "{{ kv('WHATSAPP_GROUP_ID') }}"
          DADOS_ARQUIVO: "novo_formulario.json"
        beforeCommands:
          - pip install requests python-dotenv
        commands:
          - python flow_envio_auditoria/workflow/scripts/vidibr/notificar_whatsapp.py
disabled: false
