id: envio_resultados
namespace: company.team

triggers:
  - id: agendamento_cheio
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 11,13,15,18 * * 1-6"
    timezone: "America/Sao_Paulo"
    
  - id: agendamento_quebrado
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "30 16 * * 1-6"
    timezone: "America/Sao_Paulo"

  - id: whatsapp_comando_parcial
    type: io.kestra.plugin.core.trigger.Webhook
    key: 3NnevMX2
    conditions:
      - type: io.kestra.plugin.core.condition.Expression
        expression: |
          {{ 
            (trigger.body.data.key.fromMe == false) and 
            (
              (trigger.body.data.message.conversation | default('') | lower == 'parcial loja') or 
              (trigger.body.data.message.extendedTextMessage.text | default('') | lower == 'parcial loja')
            )
          }}

tasks:
  - id: wdir
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: sync_github
        type: io.kestra.plugin.git.SyncNamespaceFiles
        username: "{{ kv('GITHUB_USER') }}"
        password: "{{ kv('GITHUB_PASS') }}"
        url: https://github.com/raffaelhfarias/auto_kestra
        branch: main
        namespace: company.team
        gitDirectory: .
        dryRun: false

      - id: extracao_loja
        type: io.kestra.plugin.scripts.python.Commands
        containerImage: mcr.microsoft.com/playwright/python:v1.57.0-noble
        env:
          LOJA_USER: "{{ kv('LOJA_USER') }}"
          LOJA_PASS: "{{ kv('LOJA_PASS') }}"
        beforeCommands:
          - pip install -r flow_envio_resultados/requirements.txt
        commands:
          - export PYTHONPATH=flow_envio_resultados && python flow_envio_resultados/workflow/scripts/loja.py
        outputFiles:
          - "resultado_loja.json"

      - id: notificar_whatsapp
        type: io.kestra.plugin.scripts.python.Commands
        containerImage: python:3.11-slim
        inputFiles:
          dados.json: "{{ outputs.extracao_loja.outputFiles['resultado_loja.json'] }}"
        env:
          DADOS_ARQUIVO: "dados.json"
          LOJA_META: "{{ kv('LOJA_META') | default('0') }}"
          EVOLUTION_API_URL: "{{ kv('EVOLUTION_API_URL') }}"
          EVOLUTION_API_KEY: "{{ kv('EVOLUTION_API_KEY') }}"
          EVOLUTION_INSTANCE: "{{ kv('EVOLUTION_INSTANCE') }}"
          WHATSAPP_GROUP_LOJA: "{{ kv('WHATSAPP_GROUP_LOJA') }}"
        beforeCommands:
          - pip install requests python-dotenv
        commands:
          - python flow_envio_resultados/workflow/scripts/notificar_whatsapp.py
disabled: false
