id: orquestrador_whatsapp
namespace: company.team
description: |
  Orquestrador central que recebe webhooks da Evolution API e direciona para os fluxos corretos baseados em palavras-chave.

triggers:
  - id: whatsapp_central
    type: io.kestra.plugin.core.trigger.Webhook
    key: whatsapp_central
    conditions:
      - type: io.kestra.plugin.core.condition.Expression
        # Ignora mensagens enviadas pelo próprio bot (fromMe=true)
        expression: "{{ trigger.body.data.key.fromMe == false }}"

tasks:
  - id: extrair_mensagem
    type: io.kestra.plugin.core.debug.Return
    format: "{{ trigger.body.data.message.conversation ?? trigger.body.data.message.extendedTextMessage.text ?? '' }}"

  - id: log_recebimento
    type: io.kestra.plugin.core.log.Log
    message: |
      Mensagem recebida de: {{ trigger.body.data.pushName }} ({{ trigger.body.data.key.remoteJid }})
      DEBUG Mensagem extraída: '{{ outputs.extrair_mensagem.value }}'
      DEBUG Keys: {{ trigger.body.data.message }}

  - id: roteamento
    type: io.kestra.plugin.core.flow.Switch
    value: "{{ outputs.extrair_mensagem.value | lower | trim }}"
    cases:
      # === PARCIAL AUDITORIA ===
      "parcial auditoria":
        - id: trigger_auditoria_debug
          type: io.kestra.plugin.core.log.Log
          message: "DEBUG: Recebido comando parcial auditoria. Disparando subflow envio_auditoria..."
        - id: trigger_auditoria
          type: io.kestra.plugin.core.flow.Subflow
          namespace: company.team
          flowId: envio_auditoria
          wait: false # Não espera terminar, apenas dispara

      # === PARCIAL LOJA ===
      "parcial loja":
        - id: trigger_loja
          type: io.kestra.plugin.core.flow.Subflow
          namespace: company.team
          flowId: envio_resultados
          wait: false

      # === PARCIAL VD ===
      "parcial vd":
        - id: trigger_vd
          type: io.kestra.plugin.core.flow.Subflow
          namespace: company.team
          flowId: envio_resultados_vd
          inputs:
            modo: "completo"
          wait: false

    defaults:
      - id: sem_comando_valido
        type: io.kestra.plugin.core.log.Log
        message: "Nenhum comando conhecido detectado na mensagem."
